Chain .then in scripts
browserstack/cucumber-js-browserstack pull request #40
Opened 2022-10-11 06:23 UTC by 07souravkunda

2022-10-11 08:10 UTC, kamal-kaur04 approved these changes

2022-10-11 14:59 UTC, karanshah-browserstack requested changes

2022-10-11 14:59 UTC, karanshah-browserstack commented on conf/parallel.conf.js
>      'browserstack.use_w3c': true,
Please correct this cap  in all conf as this is sel 4 branch

2022-10-12 09:10 UTC, karanshah-browserstack approved these changes

2022-10-12 12:39 UTC, merged