Changes in yml
browserstack/cucumber-js-browserstack pull request #43
Opened 2022-12-13 07:26 UTC by agarneha1331

2022-12-22 06:17 UTC, 07souravkunda requested changes

2022-12-22 06:17 UTC, 07souravkunda commented on browserstack.yml
> +# `buildIdentifer` is a unique id to differentiate every execution that gets appended to
spell

2022-12-22 06:17 UTC, 07souravkunda commented on browserstack.yml
> +# buildName. Choose your buildIdentifier format from the the available expressions:
spell

2022-12-28 13:19 UTC, karanshah-browserstack approved these changes

2022-12-30 11:12 UTC, francisf approved these changes

2022-12-30 11:12 UTC, merged